Feature
airswap/airswap-protocols pull request #750
Opened 2022-01-05 05:26 UTC by francisldn

#747 add withdrawWithSignature function. Edited IPool.sol, Pool.sol and unit.js files.

2022-01-07 05:27 UTC, AboldUSER requested changes
Looks good, just added some formatting updates.
Also I think for 100% test coverage you'll need a test that reverts when a signature is used a second time on withdrawWithSignature

2022-01-07 05:27 UTC, AboldUSER commented on source/pool/contracts/Pool.sol
> +
There is an extra empty line here that can be deleted

2022-01-07 05:27 UTC, AboldUSER commented on source/pool/contracts/Pool.sol
> +
Three empty lines that can be deleted

2022-01-07 05:27 UTC, AboldUSER commented on source/pool/contracts/interfaces/IPool.sol
> +  function withdrawWithSignature(
I suggest moving the function into the same order as in the actual contract

2022-01-07 05:27 UTC, AboldUSER commented on source/pool/test/integration.js
An empty line that can be deleted

2022-01-07 05:27 UTC, AboldUSER commented on source/pool/test/integration.js
> +
An empty line that can be deleted

2022-01-07 05:27 UTC, AboldUSER commented on source/pool/test/unit.js
> +    it('withdrawWithSignature does not revert with signer who is admin', async () => {
This can be named `withdrawWithSignature success` to align with similar withdraw function tests

2022-01-07 19:16 UTC, francisldn commented
Thanks for your comments @AboldUSER. I have added 1 more test to improve test coverage and tidied up the formatting issues in contracts and test files.

2022-01-08 00:26 UTC, francisldn commented
The PR is ready for further review. I merged the changes in main, added a test in unit test file to bring the test coverage to 100% and did the formatting changes as suggested. No change to the integration test file as per the main branch.

2022-01-08 02:29 UTC, AboldUSER approved these changes

2022-01-08 02:29 UTC, merged